require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CdsStructuresController do

  # This should return the minimal set of attributes required to create a valid
  # CdsStructure. As you add validations to CdsStructure, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CdsStructuresController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cds_structures as @cds_structures" do
      cds_structure = CdsStructure.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cds_structures).should eq([cds_structure])
    end
  end

  describe "GET show" do
    it "assigns the requested cds_structure as @cds_structure" do
      cds_structure = CdsStructure.create! valid_attributes
      get :show, {:id => cds_structure.to_param}, valid_session
      assigns(:cds_structure).should eq(cds_structure)
    end
  end

  describe "GET new" do
    it "assigns a new cds_structure as @cds_structure" do
      get :new, {}, valid_session
      assigns(:cds_structure).should be_a_new(CdsStructure)
    end
  end

  describe "GET edit" do
    it "assigns the requested cds_structure as @cds_structure" do
      cds_structure = CdsStructure.create! valid_attributes
      get :edit, {:id => cds_structure.to_param}, valid_session
      assigns(:cds_structure).should eq(cds_structure)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CdsStructure" do
        expect {
          post :create, {:cds_structure => valid_attributes}, valid_session
        }.to change(CdsStructure, :count).by(1)
      end

      it "assigns a newly created cds_structure as @cds_structure" do
        post :create, {:cds_structure => valid_attributes}, valid_session
        assigns(:cds_structure).should be_a(CdsStructure)
        assigns(:cds_structure).should be_persisted
      end

      it "redirects to the created cds_structure" do
        post :create, {:cds_structure => valid_attributes}, valid_session
        response.should redirect_to(CdsStructure.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cds_structure as @cds_structure" do
        # Trigger the behavior that occurs when invalid params are submitted
        CdsStructure.any_instance.stub(:save).and_return(false)
        post :create, {:cds_structure => { "name" => "invalid value" }}, valid_session
        assigns(:cds_structure).should be_a_new(CdsStructure)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CdsStructure.any_instance.stub(:save).and_return(false)
        post :create, {:cds_structure => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cds_structure" do
        cds_structure = CdsStructure.create! valid_attributes
        # Assuming there are no other cds_structures in the database, this
        # specifies that the CdsStructure created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CdsStructure.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => cds_structure.to_param, :cds_structure => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested cds_structure as @cds_structure" do
        cds_structure = CdsStructure.create! valid_attributes
        put :update, {:id => cds_structure.to_param, :cds_structure => valid_attributes}, valid_session
        assigns(:cds_structure).should eq(cds_structure)
      end

      it "redirects to the cds_structure" do
        cds_structure = CdsStructure.create! valid_attributes
        put :update, {:id => cds_structure.to_param, :cds_structure => valid_attributes}, valid_session
        response.should redirect_to(cds_structure)
      end
    end

    describe "with invalid params" do
      it "assigns the cds_structure as @cds_structure" do
        cds_structure = CdsStructure.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CdsStructure.any_instance.stub(:save).and_return(false)
        put :update, {:id => cds_structure.to_param, :cds_structure => { "name" => "invalid value" }}, valid_session
        assigns(:cds_structure).should eq(cds_structure)
      end

      it "re-renders the 'edit' template" do
        cds_structure = CdsStructure.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CdsStructure.any_instance.stub(:save).and_return(false)
        put :update, {:id => cds_structure.to_param, :cds_structure => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cds_structure" do
      cds_structure = CdsStructure.create! valid_attributes
      expect {
        delete :destroy, {:id => cds_structure.to_param}, valid_session
      }.to change(CdsStructure, :count).by(-1)
    end

    it "redirects to the cds_structures list" do
      cds_structure = CdsStructure.create! valid_attributes
      delete :destroy, {:id => cds_structure.to_param}, valid_session
      response.should redirect_to(cds_structures_url)
    end
  end

end
